name: Sphinx

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v1
      - run: pip install sphinx
      - run: pip install myst-parser
      - run: pip install sphinx-rtd-theme
      - run: sudo apt install gettext
      - run: pip install sphinx-intl
      - run: pip install gitinclude
      - name: sphinx build(ja)
        working-directory: ./docs
        run: sphinx-build . ../public/ja
      - name: sphinx build(en)
        working-directory: ./docs
        run: sphinx-build . ../public/en -D language=en -A language=en
      - name: copy index.html
        run: cp docs/index.html public/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
